Contact page
dsc-ateneo-de-manila-university/hackfest-website pull request #14
Opened 2020-11-05 19:28 UTC by Znarfois

- [x] Contact Section
- [x] Stay up-to-date-section
- [ ] Clickable
- [ ] Responsive

2020-11-06 01:50 UTC, Hjkun77 commented
@Znarfois so is this still in progress? Please make it responsive and clickable first

Also instead of `npm install` can you use `yarn install` so that consistent with @tanzellgo

2020-11-06 01:51 UTC, Hjkun77 commented
Why does your branch still have the old files? Did you git fetch origin before working on this branch?

2020-11-06 01:54 UTC, Hjkun77 requested changes
Fix the code and remove the images from the previous version since we don't need them

2020-11-06 01:54 UTC, Hjkun77 commented on src/pages/Contact.vue
> +                    <p>christopher.lao@obf.ateneo.edu</p>
change this to a `a href="mailto:christopher.lao@obf.ateneo.edu">christopher.lao@obf.ateneo.edu</a>`

2020-11-06 01:54 UTC, Hjkun77 commented on src/pages/Contact.vue
> +                        <p>@dsc.ateneo</p>
use ahref as well for linking

2020-11-06 02:16 UTC, Hjkun77 commented
Remove 
`src/assets/Ellipse 46.png`
`src/assets/frabau.png`
`src/assets/shad.png`

2020-11-07 03:28 UTC, tanzellgo approved these changes
nice job bro just did some minor hot fix

2020-11-07 03:35 UTC, merged